file_format: "1"
id: TAKA
name: TAKA
type: shield
url: https://github.com/OLIVIOU1224/zmk-config-TAKA
requires: [nice_nano_v2]
exposes: [SSD1306(i2c)]
features:
  - keys
  - display
siblings:
  - TAKA_left
  - TAKA_right
